name: 'Milestone Check'
description: 'Check if any milestone is set in a GitHub PR'
inputs:
  token:
    description: Auth token used to add status commits.
    default: "${{ github.token }}"
    required: true
  status_context:
    description: The context for the status. Default is \"Milestone Check\"
    default: "Milestone Check"
    required: true
runs:
  using: 'node12'
  main: 'index.js'